import type {
  Lead,
  Campaign,
  Conversation,
  VoiceProfile,
  ICP,
  IntentSignal,
  OutreachMessage,
} from "@/types/scouting"

const DEMO_USER = "demo-user"

// ─── Voice profile ──────────────────────────────────────────────────────────

export const DEMO_VOICE_PROFILE: VoiceProfile = {
  id: "voice-1",
  userId: DEMO_USER,
  formalityLevel: 2,
  avgMessageLength: 320,
  openingStyle: "observation",
  usesHumor: true,
  characteristicPhrases: ["quick one", "noticed you", "worth a chat?", "no pitch"],
  phrasesToAvoid: ["I hope this email finds you well", "circle back", "synergy", "touch base"],
  signOffStyle: "Cheers, Maya",
  trainingMessages: [
    "Hey {{name}} — noticed {{company}} just shipped your API v2. Big move. We help teams like yours turn that launch momentum into pipeline. Worth a quick chat?",
    "Quick one {{name}}: saw you're hiring 3 AEs. Usually means the sales engine is heating up. Curious how you're handling outbound right now?",
  ],
  version: 3,
  createdAt: "2026-05-01T10:00:00Z",
  updatedAt: "2026-06-20T10:00:00Z",
}

// ─── ICPs ───────────────────────────────────────────────────────────────────

export const DEMO_ICPS: ICP[] = [
  {
    id: "icp-1",
    user_id: DEMO_USER,
    name: "Series A DevTools — Heads of Growth",
    industries: ["SaaS", "DevTools"],
    employeeMin: 30,
    employeeMax: 150,
    fundingStages: ["series_a"],
    geographies: ["United States", "Canada"],
    jobTitles: ["Head of Growth", "VP Sales", "Founder"],
    keywords: ["uses Salesforce", "hiring AEs", "PLG motion"],
    exclusions: ["agencies", "current customers"],
    createdAt: "2026-05-02T10:00:00Z",
    updatedAt: "2026-06-10T10:00:00Z",
  },
  {
    id: "icp-2",
    user_id: DEMO_USER,
    name: "Seed Fintech — Founders",
    industries: ["Fintech", "SaaS"],
    employeeMin: 10,
    employeeMax: 60,
    fundingStages: ["seed", "pre_seed"],
    geographies: ["United States", "United Kingdom"],
    jobTitles: ["Founder", "CEO", "Head of Sales"],
    keywords: ["recently raised", "B2B"],
    exclusions: [],
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-15T10:00:00Z",
  },
]

// ─── Helper to build signals ────────────────────────────────────────────────

function sig(
  type: IntentSignal["type"],
  strength: IntentSignal["strength"],
  label: string,
  detail: string,
): IntentSignal {
  return { type, strength, label, detail, detectedAt: "2026-06-25T09:00:00Z" }
}

// ─── Leads ──────────────────────────────────────────────────────────────────

export const DEMO_LEADS: Lead[] = [
  {
    id: "lead-1",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "David",
    lastName: "Okafor",
    title: "VP of Sales",
    company: "Latchkey",
    companyDomain: "latchkey.io",
    linkedinUrl: "https://linkedin.com/in/davidokafor",
    avatarColor: "bg-indigo-500",
    employeeCount: 84,
    fundingStage: "series_a",
    lastFundingDate: "2026-04-12",
    location: "San Francisco, CA",
    techStack: ["Salesforce", "Outreach", "AWS"],
    lastActivity: "Posted about scaling outbound 2 days ago",
    icpScore: 38,
    intentScore: 36,
    engagementScore: 17,
    totalScore: 91,
    intentSignals: [
      sig("funding", "strong", "Raised $14M Series A", "Announced April 2026, led by Battery Ventures"),
      sig("hiring", "strong", "Hiring 4 AEs", "4 open Account Executive roles posted this month"),
      sig("content", "medium", "Posted on outbound", "Shared a post about outbound efficiency 2 days ago"),
    ],
    researchBrief: {
      hooks: [
        "Just closed a $14M Series A — sales team is scaling fast",
        "Posted 2 days ago about outbound efficiency being their #1 problem",
        "4 open AE roles signal a ramping sales org with onboarding pain",
      ],
      companyContext:
        "Latchkey is a Series A access-management SaaS (84 employees) that raised $14M in April 2026. They are doubling their sales team this quarter.",
      personalContext:
        "David has been VP Sales for 14 months, came from Okta, and posts regularly about sales efficiency and rep ramp time.",
      recommendedAngle:
        "Lead with the outbound-efficiency angle he posted about. Tie Scouting to faster rep ramp during a scaling phase.",
      sources: ["linkedin.com/in/davidokafor", "techcrunch.com/latchkey-series-a", "latchkey.io/careers"],
      generatedAt: "2026-06-25T09:10:00Z",
    },
    stage: "replied",
    status: "replied",
    createdAt: "2026-06-20T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-25T14:00:00Z",
  },
  {
    id: "lead-2",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Priya",
    lastName: "Raman",
    title: "Head of Growth",
    company: "Cohesion Labs",
    companyDomain: "cohesionlabs.com",
    linkedinUrl: "https://linkedin.com/in/priyaraman",
    avatarColor: "bg-rose-500",
    employeeCount: 47,
    fundingStage: "series_a",
    lastFundingDate: "2026-02-20",
    location: "Austin, TX",
    techStack: ["HubSpot", "Apollo", "Vercel"],
    lastActivity: "Commented on a post about PLG vs sales-led 1 day ago",
    icpScore: 36,
    intentScore: 30,
    engagementScore: 16,
    totalScore: 82,
    intentSignals: [
      sig("hiring", "strong", "Hiring 2 SDRs", "Building an outbound team for the first time"),
      sig("content", "medium", "Engaged on PLG content", "Commented on a sales-led vs PLG debate yesterday"),
    ],
    researchBrief: {
      hooks: [
        "Building an outbound team from scratch — hiring 2 SDRs",
        "Just commented that PLG alone has plateaued for them",
        "Series A in Feb 2026, now under pressure to add a sales motion",
      ],
      companyContext:
        "Cohesion Labs is a 47-person collaboration SaaS, Series A in Feb 2026. Historically PLG, now layering on outbound.",
      personalContext:
        "Priya owns growth end-to-end and is actively debating PLG vs sales-led motions in public.",
      recommendedAngle:
        "Position Scouting as the fastest way to stand up outbound without a full SDR team while she figures out the motion.",
      sources: ["linkedin.com/in/priyaraman", "cohesionlabs.com/careers"],
      generatedAt: "2026-06-25T09:12:00Z",
    },
    stage: "messaged",
    status: "active",
    createdAt: "2026-06-21T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-24T11:00:00Z",
  },
  {
    id: "lead-3",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Marcus",
    lastName: "Bauer",
    title: "Founder & CEO",
    company: "Ledgerwise",
    companyDomain: "ledgerwise.io",
    linkedinUrl: "https://linkedin.com/in/marcusbauer",
    avatarColor: "bg-emerald-500",
    employeeCount: 22,
    fundingStage: "seed",
    lastFundingDate: "2026-05-30",
    location: "New York, NY",
    techStack: ["Pipedrive", "Stripe", "Retool"],
    lastActivity: "Announced seed round 4 days ago",
    icpScore: 34,
    intentScore: 33,
    engagementScore: 14,
    totalScore: 81,
    intentSignals: [
      sig("funding", "strong", "Raised $4M Seed", "Closed last week, plans to hire GTM"),
      sig("growth", "medium", "Headcount +40% in 6mo", "Grew from 15 to 22 employees"),
    ],
    researchBrief: {
      hooks: [
        "Just announced a $4M seed — about to build GTM",
        "Headcount up 40% in 6 months, scaling phase",
        "Founder still personally doing sales — prime time for leverage",
      ],
      companyContext:
        "Ledgerwise is a 22-person fintech reconciliation tool, seed-funded last week.",
      personalContext:
        "Marcus is a technical founder doing his own outbound and has openly asked his network for GTM advice.",
      recommendedAngle:
        "Founder-to-founder: Scouting replaces the SDR he can't yet afford while he focuses on product.",
      sources: ["linkedin.com/in/marcusbauer", "ledgerwise.io"],
      generatedAt: "2026-06-25T09:15:00Z",
    },
    stage: "connection_sent",
    status: "active",
    createdAt: "2026-06-23T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-25T09:30:00Z",
  },
  {
    id: "lead-4",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Sofia",
    lastName: "Greco",
    title: "VP Revenue",
    company: "Pingboard AI",
    companyDomain: "pingboard.ai",
    linkedinUrl: "https://linkedin.com/in/sofiagreco",
    avatarColor: "bg-sky-500",
    employeeCount: 120,
    fundingStage: "series_b_plus",
    lastFundingDate: "2025-11-10",
    location: "Remote (US)",
    techStack: ["Salesforce", "Gong", "Snowflake"],
    lastActivity: "Shared a hiring post for an SDR manager 3 days ago",
    icpScore: 31,
    intentScore: 28,
    engagementScore: 15,
    totalScore: 74,
    intentSignals: [
      sig("hiring", "medium", "Hiring SDR Manager", "Signals an expanding outbound team"),
      sig("tech", "weak", "Adopted Gong", "Recently rolled out conversation intelligence"),
    ],
    researchBrief: null,
    stage: "prospected",
    status: "active",
    createdAt: "2026-06-24T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: null,
  },
  {
    id: "lead-5",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Tomás",
    lastName: "Vidal",
    title: "Head of Sales",
    company: "Quanta Metrics",
    companyDomain: "quantametrics.com",
    linkedinUrl: "https://linkedin.com/in/tomasvidal",
    avatarColor: "bg-amber-500",
    employeeCount: 65,
    fundingStage: "series_a",
    lastFundingDate: "2026-01-15",
    location: "Toronto, CA",
    techStack: ["HubSpot", "Clay", "GCP"],
    lastActivity: "Liked a competitor's post about cold outreach 5 days ago",
    icpScore: 33,
    intentScore: 22,
    engagementScore: 13,
    totalScore: 68,
    intentSignals: [
      sig("competitor", "medium", "Engaged w/ competitor", "Liked a Dripify post about outreach last week"),
    ],
    researchBrief: null,
    stage: "prospected",
    status: "active",
    createdAt: "2026-06-24T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: null,
  },
  {
    id: "lead-6",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Hannah",
    lastName: "Cole",
    title: "Founder",
    company: "Driftwood Data",
    companyDomain: "driftwood.dev",
    linkedinUrl: "https://linkedin.com/in/hannahcole",
    avatarColor: "bg-violet-500",
    employeeCount: 18,
    fundingStage: "seed",
    lastFundingDate: "2026-03-01",
    location: "London, UK",
    techStack: ["Pipedrive", "Supabase"],
    lastActivity: "Posted about hating cold outreach tools 6 days ago",
    icpScore: 30,
    intentScore: 25,
    engagementScore: 11,
    totalScore: 66,
    intentSignals: [
      sig("content", "medium", "Pain signal post", "Posted that current outreach tools feel spammy"),
      sig("growth", "weak", "Slow steady growth", "Stable 18-person team"),
    ],
    researchBrief: null,
    stage: "meeting_booked",
    status: "booked",
    createdAt: "2026-06-18T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-24T16:00:00Z",
  },
  {
    id: "lead-7",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Owen",
    lastName: "Reyes",
    title: "RevOps Lead",
    company: "Stackline Health",
    companyDomain: "stackline.health",
    linkedinUrl: "https://linkedin.com/in/owenreyes",
    avatarColor: "bg-teal-500",
    employeeCount: 140,
    fundingStage: "series_b_plus",
    lastFundingDate: "2025-09-01",
    location: "Boston, MA",
    techStack: ["Salesforce", "Outreach", "Looker"],
    lastActivity: "Connected, no reply yet",
    icpScore: 29,
    intentScore: 18,
    engagementScore: 12,
    totalScore: 59,
    intentSignals: [],
    researchBrief: null,
    stage: "connected",
    status: "active",
    createdAt: "2026-06-19T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-22T10:00:00Z",
  },
  {
    id: "lead-8",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Lena",
    lastName: "Hoffmann",
    title: "Head of Growth",
    company: "Northwind Cloud",
    companyDomain: "northwind.cloud",
    linkedinUrl: "https://linkedin.com/in/lenahoffmann",
    avatarColor: "bg-fuchsia-500",
    employeeCount: 95,
    fundingStage: "series_a",
    lastFundingDate: "2026-03-22",
    location: "Berlin, DE",
    techStack: ["HubSpot", "Metabase", "AWS"],
    lastActivity: "Replied: not the right quarter",
    icpScore: 35,
    intentScore: 20,
    engagementScore: 14,
    totalScore: 69,
    intentSignals: [sig("funding", "medium", "Raised Series A", "€11M round in March 2026")],
    researchBrief: null,
    stage: "nurture",
    status: "nurture",
    createdAt: "2026-06-15T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-23T10:00:00Z",
  },
  {
    id: "lead-9",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Raj",
    lastName: "Mehta",
    title: "Co-founder",
    company: "Flowstate",
    companyDomain: "flowstate.app",
    linkedinUrl: "https://linkedin.com/in/rajmehta",
    avatarColor: "bg-orange-500",
    employeeCount: 31,
    fundingStage: "seed",
    lastFundingDate: "2026-04-28",
    location: "Remote (Global)",
    techStack: ["Pipedrive", "Linear", "Fly.io"],
    lastActivity: "Qualified on intro call",
    icpScore: 37,
    intentScore: 31,
    engagementScore: 18,
    totalScore: 86,
    intentSignals: [
      sig("funding", "strong", "Raised $6M Seed", "Closed in late April"),
      sig("hiring", "medium", "Hiring first sales rep", "Posted a Founding AE role"),
    ],
    researchBrief: null,
    stage: "qualified",
    status: "active",
    createdAt: "2026-06-12T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-24T10:00:00Z",
  },
  {
    id: "lead-10",
    userId: DEMO_USER,
    campaignId: "camp-1",
    firstName: "Grace",
    lastName: "Liu",
    title: "VP Sales",
    company: "Beacon Security",
    companyDomain: "beaconsec.io",
    linkedinUrl: "https://linkedin.com/in/graceliu",
    avatarColor: "bg-cyan-500",
    employeeCount: 110,
    fundingStage: "series_b_plus",
    lastFundingDate: "2025-12-05",
    location: "Seattle, WA",
    techStack: ["Salesforce", "Salesloft"],
    lastActivity: "Closed — became a customer",
    icpScore: 32,
    intentScore: 29,
    engagementScore: 19,
    totalScore: 80,
    intentSignals: [sig("growth", "medium", "Headcount +25%", "Grew from 88 to 110 in 6 months")],
    researchBrief: null,
    stage: "closed_won",
    status: "closed_won",
    createdAt: "2026-05-28T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
    lastContactedAt: "2026-06-20T10:00:00Z",
  },
]

// ─── Campaigns ──────────────────────────────────────────────────────────────

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-1",
    userId: DEMO_USER,
    name: "Series A DevTools Q3",
    description: "Heads of Growth & VP Sales at recently-funded DevTools companies.",
    type: "cold_outreach",
    status: "active",
    icpId: "icp-1",
    dailyConnectionLimit: 20,
    dailyMessageLimit: 50,
    activeHoursStart: "09:00",
    activeHoursEnd: "18:00",
    activeDays: ["mon", "tue", "wed", "thu", "fri"],
    timezone: "America/New_York",
    sequence: [],
    totalLeads: 180,
    connectionsSent: 142,
    connectionsAccepted: 58,
    messagesSent: 121,
    repliesReceived: 19,
    meetingsBooked: 7,
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
  },
  {
    id: "camp-2",
    userId: DEMO_USER,
    name: "Seed Fintech Founders",
    description: "Founders of seed-stage fintech who just raised.",
    type: "event_based",
    status: "active",
    icpId: "icp-2",
    dailyConnectionLimit: 15,
    dailyMessageLimit: 40,
    activeHoursStart: "08:00",
    activeHoursEnd: "17:00",
    activeDays: ["mon", "tue", "wed", "thu", "fri"],
    timezone: "America/New_York",
    sequence: [],
    totalLeads: 95,
    connectionsSent: 61,
    connectionsAccepted: 27,
    messagesSent: 49,
    repliesReceived: 9,
    meetingsBooked: 3,
    createdAt: "2026-06-10T10:00:00Z",
    updatedAt: "2026-06-26T10:00:00Z",
  },
  {
    id: "camp-3",
    userId: DEMO_USER,
    name: "Cold Q2 Re-engagement",
    description: "Leads that went cold 90+ days ago — fresh angle.",
    type: "re_engagement",
    status: "paused",
    icpId: "icp-1",
    dailyConnectionLimit: 10,
    dailyMessageLimit: 30,
    activeHoursStart: "09:00",
    activeHoursEnd: "17:00",
    activeDays: ["tue", "wed", "thu"],
    timezone: "America/New_York",
    sequence: [],
    totalLeads: 60,
    connectionsSent: 60,
    connectionsAccepted: 22,
    messagesSent: 38,
    repliesReceived: 4,
    meetingsBooked: 1,
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-06-22T10:00:00Z",
  },
]

// ─── Inbox conversations ────────────────────────────────────────────────────

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    leadId: "lead-1",
    campaignId: "camp-1",
    classification: "hot",
    unread: true,
    lastMessageAt: "2026-06-26T13:40:00Z",
    messages: [
      {
        id: "m1",
        direction: "outbound",
        content:
          "Hey David — saw Latchkey just closed your Series A, congrats. You posted last week about outbound efficiency being the bottleneck. We help scaling sales teams research + personalize every touch so reps ramp faster. Worth a quick chat?",
        timestamp: "2026-06-25T14:00:00Z",
      },
      {
        id: "m2",
        direction: "inbound",
        content:
          "Hey, yeah this is timely — we're drowning in manual research right now. Send me some info, or better yet do you have time this week?",
        timestamp: "2026-06-26T13:40:00Z",
      },
    ],
    suggestedReplies: [
      {
        label: "Book the meeting",
        tone: "aggressive",
        content:
          "Love it. Here's my calendar — grab whatever works: cal.com/maya/30. I'll come ready with a few specific ideas for Latchkey's outbound.",
      },
      {
        label: "Value first",
        tone: "soft",
        content:
          "Awesome. I'll send a 2-min Loom showing how we'd research your exact ICP, then we can find time. What's the #1 segment you're targeting right now?",
      },
      {
        label: "Clarify",
        tone: "clarifying",
        content:
          "Happy to. Quick q so I tailor it — is the manual research mostly for net-new prospecting, or personalizing follow-ups to existing pipeline?",
      },
    ],
  },
  {
    id: "conv-2",
    leadId: "lead-2",
    campaignId: "camp-1",
    classification: "warm",
    unread: true,
    lastMessageAt: "2026-06-26T11:10:00Z",
    messages: [
      {
        id: "m1",
        direction: "outbound",
        content:
          "Hi Priya — saw you're standing up outbound at Cohesion for the first time. Most PLG teams hit a wall here. We help you launch personalized outbound without hiring a full SDR pod. Open to comparing notes?",
        timestamp: "2026-06-24T11:00:00Z",
      },
      {
        id: "m2",
        direction: "inbound",
        content: "Interesting — what does it actually do differently from Apollo sequences?",
        timestamp: "2026-06-26T11:10:00Z",
      },
    ],
    suggestedReplies: [
      {
        label: "Differentiate + book",
        tone: "aggressive",
        content:
          "Great question. Apollo blasts templates; Scouting researches each lead live and writes in your voice — replies, not volume. Easier to show than tell — 15 min Thursday? cal.com/maya/30",
      },
      {
        label: "Send proof",
        tone: "soft",
        content:
          "Short version: real-time research per lead + voice matching, so messages don't read like sequences. I'll send a side-by-side example from a PLG team like yours.",
      },
      {
        label: "Clarify need",
        tone: "clarifying",
        content:
          "Depends what's frustrating you about Apollo today — is it reply rates, the manual personalization, or list quality?",
      },
    ],
  },
  {
    id: "conv-3",
    leadId: "lead-8",
    campaignId: "camp-1",
    classification: "nurture",
    unread: false,
    lastMessageAt: "2026-06-23T15:00:00Z",
    messages: [
      {
        id: "m1",
        direction: "outbound",
        content:
          "Hi Lena — congrats on the Series A. We help growth leads turn funding momentum into outbound pipeline. Worth a look?",
        timestamp: "2026-06-23T10:00:00Z",
      },
      {
        id: "m2",
        direction: "inbound",
        content: "Thanks! Not the right quarter for us, but check back in Q4 — we'll be hiring SDRs then.",
        timestamp: "2026-06-23T15:00:00Z",
      },
    ],
    suggestedReplies: [
      {
        label: "Schedule re-engage",
        tone: "soft",
        content:
          "Totally get it — I'll ping you early Q4 when you're staffing up. In the meantime I'll send the occasional outbound benchmark in case it's useful. Congrats again on the round!",
      },
      {
        label: "Stay warm",
        tone: "clarifying",
        content:
          "Makes sense. When you do hire SDRs in Q4, is the plan inbound-led or outbound-led? Helps me send the right things your way closer to then.",
      },
    ],
  },
  {
    id: "conv-4",
    leadId: "lead-5",
    campaignId: "camp-1",
    classification: "out_of_office",
    unread: false,
    lastMessageAt: "2026-06-25T08:00:00Z",
    messages: [
      {
        id: "m1",
        direction: "outbound",
        content:
          "Hi Tomás — noticed you've been looking at outreach tooling. We take a research-first approach vs the spray-and-pray crowd. Worth 15 min?",
        timestamp: "2026-06-24T16:00:00Z",
      },
      {
        id: "m2",
        direction: "inbound",
        content:
          "I'm out of office until July 1st with limited access to email. I'll respond when I'm back.",
        timestamp: "2026-06-25T08:00:00Z",
      },
    ],
    suggestedReplies: [
      {
        label: "Auto-pause",
        tone: "soft",
        content:
          "No rush at all, Tomás — enjoy the time off. I'll follow up the week of July 1st.",
      },
    ],
  },
]

// ─── Outbound messages (Send queue) ─────────────────────────────────────────

function msg(
  id: string,
  leadId: string,
  step: number,
  type: OutreachMessage["type"],
  content: string,
  status: OutreachMessage["status"],
  hooks: string[],
): OutreachMessage {
  return {
    id,
    leadId,
    campaignId: "camp-1",
    sequenceStep: step,
    type,
    direction: "outbound",
    content,
    generatedBy: "ai",
    personalizationHooks: hooks,
    confidence: 88,
    quality: { verdict: "approve", reasons: ["Personalized, concise, human-sounding"] },
    variant: null,
    status,
    charCount: content.length,
    sentAt: null,
    createdAt: "2026-06-26T09:00:00Z",
  }
}

export const DEMO_MESSAGES: OutreachMessage[] = [
  msg(
    "msg-1",
    "lead-3",
    1,
    "connection_request",
    "Hey Marcus — just saw Ledgerwise closed your $4M seed, congrats. I help founders stand up outbound before they can afford an SDR. Mind if I connect?",
    "approved",
    ["Raised $4M seed"],
  ),
  msg(
    "msg-2",
    "lead-4",
    1,
    "connection_request",
    "Hi Sofia — noticed Pingboard is hiring an SDR manager. Usually means the outbound engine is heating up. We help RevOps teams research + personalize at scale. Worth connecting?",
    "draft",
    ["Hiring SDR Manager"],
  ),
  msg(
    "msg-3",
    "lead-2",
    3,
    "follow_up",
    "Following up, Priya — one stat: researched, personalized outreach gets 3-4x the reply rate of templated sequences. We get you there without adding headcount. Worth a 15-min look?",
    "approved",
    ["reply-rate angle", "social proof"],
  ),
  msg(
    "msg-4",
    "lead-5",
    1,
    "connection_request",
    "Hi Tomás — noticed you've been looking at outreach tooling. We take a research-first approach vs the spray-and-pray crowd. Mind if I connect?",
    "draft",
    ["Engaged w/ competitor"],
  ),
]

export function getLeadById(id: string): Lead | undefined {
  return DEMO_LEADS.find((l) => l.id === id)
}

export function getCampaignById(id: string): Campaign | undefined {
  return DEMO_CAMPAIGNS.find((c) => c.id === id)
}
